{% set name = "freecad" %}
{% set version = "1.2.dev" %}
{% set build_number = 1 %}
{% set sha256sum = "bca05873623c0b586a93ee5ce84d02ad6ff65a566281c592fa5894741e2e39fe" %}
{% set url = "https://github.com/FreeCAD/FreeCAD/releases/download/weekly-2026.02.11/freecad_source_weekly-2026.02.11.tar.gz" %}


package:
    name: {{ name }}
    version: {{ version }}

source:
    url: {{ url }}
    sha256: {{ sha256sum }}
    patches:
        - patches/osx_arm64_cross_compiling.patch    # [osx and arm64]

build:
    number: {{ build_number }}
    script_env:
        - USE_QT6=1
    skip: true  # [py != 314]

requirements:
    build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('libselinux') }}            # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - cmake
        - swig
        - ninja
        - sed                                    # [unix]
        - qt6-main                               # [build_platform != target_platform]
        - noqt5                                  # [build_platform != target_platform]
        - doxygen
        - lark                                   # [build_platform != target_platform]
    host:
        - coin3d
        - eigen
        - freetype
        - hdf5
        - libboost-devel
        - libspnav          # [linux]
        - lark              # [build_platform == target_platform]
        - matplotlib-base
        - noqt5
        - occt
        - pivy >=0.6.10
        - pcl
        - ply
        - pybind11
        - pyside6
        - python
        - qt6-main
        - six
        - smesh >=9.9
        - tbb-devel  # [win]
        - vtk
        - xerces-c
        - xorg-xproto   # [linux]
        - yaml-cpp
        - zlib
    run:
        - graphviz
        - gmsh
        - libspnav  # [linux]
        - numpy
        - python
        - pyside6
        - pivy >=0.6.10
        - pyyaml
        - ply
        - six
        - smesh >=9.9

test:
    commands:
        - freecadcmd -t 0 || true   # [unix and build_platform == target_platform]

about:
    home: https://www.freecad.org/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: 'FreeCAD is a parametric 3D modeler made primarily to design real-life objects of any size. '
    description: |
        FreeCAD is a general purpose feature-based, parametric 3D modeler for
        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering
        and product design but also fits a wider range of uses in engineering,
        such as architecture or other engineering specialties. It is 100% Open
        Source (LGPL2+ license) and extremely modular, allowing for very
        advanced extension and customization.
        FreeCAD is based on OpenCASCADE, a powerful geometry kernel, features an
        Open Inventor-compliant 3D scene representation model provided by the
        Coin 3D library, and a broad Python API. The interface is built with Qt.
        FreeCAD runs exactly the same way on Windows, Mac OSX, BSD and Linux
        platforms.
    doc_url: https://wiki.freecad.org/Main_Page
    dev_url: https://github.com/FreeCAD/FreeCAD

extra:
    recipe-maintainers:
        - adrianinsaval
        - looooo
